name: Wake Up Render Server

on:
  schedule:
    # Chạy mỗi 10 phút (Theo chuẩn Cron)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Cho phép bạn bấm nút chạy thủ công để test

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: |
          URL="${{ secrets.RENDER_URL }}?t=$(date +%s)"
          curl -s $URL